//First installation registration page
export const setupFormRule: any[] = [
    {
        type: 'input',
        field: 'customerName',
        title: 'username',
        info: '',
        props: {
            type: 'text',
            placeholder: 'Please enter username',
            prefixIcon: 'User',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        $required: 'Please enter username',
        value: 'iotmaster@iotsharp.net',
    },
    {
        type: 'input',
        field: 'email',
        title: 'Mailbox',
        info: '',
        props: {
            type: 'text',
            placeholder: 'Please enter your email',
            showPassword: false,
            prefixIcon: 'Message',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        validate: [
            {
                trigger: 'change',
                message: 'Please enter the correct email',
                pattern: '/^[a-z0-9]+([._\\\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9 ]*[a-z0-9]+.){1,63}[a-z0-9]+$/',
                type: 'email',
                required: true,
            },
        ],
    },
    {
        type: 'input',
        field: 'password',
        title: 'Password',
        info: '',
        props: {
            placeholder: 'Please enter password',
            showPassword: true,
            prefixIcon: 'Lock',
            type: 'password',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        value: '',
        validate: [
            {
                trigger: 'change',
                mode: 'required',
                message: 'Please enter password',
                required: true,
                type: 'string',
            },
        ],
    },
    {
        type: 'input',
        field: 'passwordCheck',
        title: 'Password confirmation',
        info: '',
        props: {
            placeholder: 'Please enter your password again',
            showPassword: true,
            prefixIcon: 'Lock',
            type: 'password',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        value: '',
        validate: [],
    },
]