export const signUpRule: any[] = [
    {
        type: 'input',
        field: 'email',
        title: 'Email',
        info: '',
        props: {
            type: 'text',
            placeholder: 'please input your email',
            showPassword: false,
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        validate: [
            {
                trigger: 'change',
                message: 'please enter your vaild email',
                pattern: /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/,
                type: 'email',
                required: true,
            },
        ],
    },
    {
        type: 'input',
        field: 'customerName',
        title: 'User name',
        info: '',
        props: {
            type: 'text',
            placeholder: 'username',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        $required: 'username',
    },
    {
        type: 'input',
        field: 'password',
        title: 'Password',
        info: '',
        props: {
            type: 'password',
            placeholder: 'password',
            showPassword: true,
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        $required: '',
    },
    {
        type: 'input',
        field: 'passwordCheck',
        title: 'Please enter password',
        info: '',
        props: {
            type: 'password',
            placeholder: 'Please enter password again',
            showPassword: true,
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        value: '',
        validate: [],
    },
    {
        type: 'input',
        field: 'tenantName',
        title: 'Tenant name',
        info: '',
        props: {
            placeholder: 'Tenant name',
            showPassword: false,
            type: 'text',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        value: '',
        validate: [{
            required: true,
            message: 'Please enter tenant name'
        }],
    },
    {
        type: 'input',
        field: 'tenantEMail',
        title: 'Tenant email',
        info: '',
        props: {
            placeholder: 'Tenant email',
            showPassword: false,
            type: 'text',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        value: '',
        validate: [
            {
                trigger: 'change',
                message: 'Please enter the correct tenant email address',
                pattern: /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/,
                type: 'email',
                required: true,
            }
        ],
    },
    {
        type: 'input',
        field: 'customerEMail',
        title: 'Customer email',
        info: '',
        props: {
            placeholder: 'Customer email',
            showPassword: false,
            type: 'text',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        value: '',
        validate: [
            {
                trigger: 'change',
                message: 'Please enter the correct customer email address',
                pattern: /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/,
                type: 'email',
                required: true,
            },
        ],
    },
    {
        type: 'input',
        field: 'phoneNumber',
        title: 'contact number',
        info: '',
        props: {
            placeholder: 'contact number',
            showPassword: false,
            type: 'text',
        },
        _fc_drag_tag: 'input',
        hidden: false,
        display: true,
        value: '',
        validate: [
            {
                required: true,
                trigger: 'blur',
                message: 'please enter a valid phone number',
                pattern: /^(1[3456789]\d{9})$/,
            },
        ],
    },
]
